// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyuwlfgqnmtfgblkihdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5dXdsZmdxbm10ZmdibGtpaGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzODU2NjcsImV4cCI6MjA2Nzk2MTY2N30.MBWHRHUyhHbJ9MvlvmEqw0Y1Dp4W5zheh29CH4F7wd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});